default-color: gold
default-prefix:
  text: [PG]
  color: light_purple
messages:
  default-currentStatus:
    text: 'Dein aktueller Status:'
    color: light_purple
blacklist:
  enabled: true
  max-strikes: 3
